version: '3'
services:
  service-registry:
    restart: on-failure
    build: service-registry
    container_name: service-registry
    image: service-registry:latest
    hostname: service-registry
    environment:
      - SPRING_APPLICATION_NAME=service-registry
    expose:
      - "9090"
    ports:
      - "9090:9090"
    networks:
      services-network-01:
        aliases:
          - service-registry
  api-gateway:
    restart: on-failure
    build: api-gateway
    container_name: api-gateway
    image: api-gateway:latest
    hostname: api-gateway
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
    ports:
      - "8080:8080"
    networks:
      services-network-01:
        aliases:
          - api-gateway
    depends_on:
      - service-registry
  service-one:
    restart: on-failure
    build: service-one
    container_name: service-one
    image: service-one:latest
    hostname: service-one
    environment:
      - SPRING_APPLICATION_NAME=service1
    ports:
      - "8081:8081"
    networks:
      services-network-01:
        aliases:
          - service-one
    depends_on:
      - service-registry
      - api-gateway
  service-two:
    restart: on-failure
    build: service-two
    container_name: service-two
    image: service-two:latest
    hostname: service-two
    environment:
      - SPRING_APPLICATION_NAME=service2
    ports:
      - "8082:8082"
    networks:
      services-network-01:
        aliases:
          - service-two
    depends_on:
      - service-registry
      - api-gateway
  service-three:
    restart: on-failure
    build: service-three
    container_name: service-three
    image: service-three:latest
    hostname: service-three
    environment:
      - SPRING_APPLICATION_NAME=service3
    ports:
      - "8083:8083"
    networks:
      services-network-01:
        aliases:
          - service-three
    depends_on:
      - service-registry
      - api-gateway

networks:
  services-network-01:
    driver: bridge