logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG
server:
  port: 8080
  
okta:
  oauth2:
    client-id: 0oaavk51pXZ0v8bUN4x6
    client-secret:  oynmqgteH6HV6wLSyGFYU9dTuhtskEaBmX66HgCA 
    issuer: https://dev-579270.okta.com/oauth2/default
    scopes:
    - openid
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://service-registry:9090/eureka/
    availability-zones:
      region1: zone1
      
spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: null
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  cloud:
    gateway:
      default-filters:
      - TokenRelay
      routes:
      - id: service1
        uri: lb://service1
        predicates:
        - Path=/service1/test1/**
        - Method=GET
        filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
        - name: Retry
          args:
            retries: 2
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/inCaseOfFailureUseThis
      - id: service2
        uri: lb://service2
        predicates:
        - Path=/service2/test2/**
        - Method=POST
        filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
        - name: Retry
          args:
            retries: 2
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/inCaseOfFailureUseThis
      - id: service3
        uri: lb://service3
        predicates:
        - Path=/service3/test3/**
        - Method=PATCH
        filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
        - name: Retry
          args:
            retries: 2
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/inCaseOfFailureUseThis
      - id: tokenValidate
        uri: http://httpbin.org/get
        predicates:
        - Path=/get
        filters:
        - name: Retry
          args:
            retries: 2
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/inCaseOfFailureUseThis
